[package]
name = "ecut"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[dependencies]
arboard = "3.5.0"
eframe = "0.31.1"
image = "0.25.6"

[profile.release]
panic = "abort"
lto = "thin"
strip = "symbols"
